# Generated by Django 6.1 on 2026-09-08 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume firma')),
                ('cui', models.CharField(blank=True, max_length=50, verbose_name='CUI')),
                ('address', models.TextField(blank=True, verbose_name='Adresa firma')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persoana contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firme',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume serviciu')),
                ('service_type', models.CharField(choices=[('office', 'La Birou'), ('studio', 'La Sediu Tapuzina'), ('home', 'La Domiciliu')], max_length=20, verbose_name='Tip serviciu')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Durata standard (minute)')),
                ('max_persons', models.IntegerField(default=10, verbose_name='Numar maxim persoane')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagine')),
            ],
            options={
                'verbose_name': 'Serviciu',
                'verbose_name_plural': 'Servicii',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Luni'), (1, 'Marti'), (2, 'Miercuri'), (3, 'Joi'), (4, 'Vineri'), (5, 'Sambata'), (6, 'Duminica')], verbose_name='Ziua')),
                ('start_time', models.TimeField(verbose_name='Ora deschidere')),
                ('end_time', models.TimeField(verbose_name='Ora inchidere')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Zi lucratoare')),
                ('lunch_break_start', models.TimeField(blank=True, null=True, verbose_name='Pauza masa - inceput')),
                ('lunch_break_end', models.TimeField(blank=True, null=True, verbose_name='Pauza masa - sfarsit')),
            ],
            options={
                'verbose_name': 'Program de lucru',
                'verbose_name_plural': 'Program de lucru',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nume contact')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefon contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email contact')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Ora inceput')),
                ('end_time', models.TimeField(verbose_name='Ora sfarsit')),
                ('number_of_persons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Numar persoane')),
                ('massage_break_start', models.TimeField(blank=True, null=True, verbose_name='Pauza masor - inceput')),
                ('massage_break_end', models.TimeField(blank=True, null=True, verbose_name='Pauza masor - sfarsit')),
                ('break_duration', models.IntegerField(default=30, verbose_name='Durata pauza (minute)')),
                ('location_address', models.TextField(verbose_name='Adresa completa')),
                ('building_name', models.CharField(blank=True, max_length=200, verbose_name='Nume cladire')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Etaj')),
                ('apartment_number', models.CharField(blank=True, max_length=20, verbose_name='Numar apartament/birou')),
                ('parking_available', models.BooleanField(default=False, verbose_name='Parcare disponibila')),
                ('parking_floor', models.CharField(blank=True, max_length=20, verbose_name='Etaj parcare')),
                ('parking_spot_number', models.CharField(blank=True, max_length=20, verbose_name='Numar loc parcare')),
                ('parking_notes', models.TextField(blank=True, verbose_name='Informatii parcare')),
                ('access_notes', models.TextField(blank=True, verbose_name='Informatii acces')),
                ('special_requests', models.TextField(blank=True, verbose_name='Cerinte speciale')),
                ('notes', models.TextField(blank=True, verbose_name='Alte observatii')),
                ('status', models.CharField(choices=[('pending', 'In asteptare'), ('confirmed', 'Confirmata'), ('cancelled', 'Anulata'), ('completed', 'Finalizata')], default='pending', max_length=20, verbose_name='Status')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token confirmare')),
                ('confirmed_by_client', models.BooleanField(default=False, verbose_name='Confirmat de client')),
                ('confirmed_by_admin', models.BooleanField(default=False, verbose_name='Confirmat de admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bookings.company', verbose_name='Firma')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service', verbose_name='Serviciu')),
            ],
            options={
                'verbose_name': 'Programare',
                'verbose_name_plural': 'Programari',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
